# Generated by Django 5.1.6 on 2025-02-27 22:10

import rateprof.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateprof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[rateprof.models.validate_three_chars]),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.IntegerField(validators=[rateprof.models.validate_semester]),
        ),
        migrations.AlterField(
            model_name='module',
            name='year',
            field=models.IntegerField(validators=[rateprof.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='identifier',
            field=models.CharField(max_length=3, unique=True, validators=[rateprof.models.validate_three_chars]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='semester',
            field=models.IntegerField(validators=[rateprof.models.validate_semester]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='year',
            field=models.IntegerField(validators=[rateprof.models.validate_year]),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('code', 'year', 'semester')},
        ),
    ]
