# Generated by Django 5.1.6 on 2025-02-27 22:26

import rateprof.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateprof', '0002_alter_module_code_alter_module_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=3, validators=[rateprof.models.validate_three_chars]),
        ),
    ]
